name: Build and Update zlib Libraries

on: [workflow_dispatch]

jobs:
  build:
    uses: JunaMeinhold/cmake-actions/.github/workflows/cmake.yml@v1.x.x
    with:
      lib-name: "zlib"
      repo: "madler/zlib"
      repo-tag: "v1.3.1"
      cmake-flags: "-DCMAKE_BUILD_TYPE=Release -DZLIB_BUILD_TESTING=OFF -DZLIB_BUILD_SHARED=ON -DZLIB_BUILD_STATIC=OFF"
      cmake-flags-windows: "-DCMAKE_SYSTEM_VERSION=10.0.26100.0"
      ndk-version: "28.1.13356709"
      bin-name-osx: "libz.dylib"
      bin-name-linux: "libz.so"
      bin-name-android: "libz.so"
      bin-name-windows: "Release/zlib.dll"
      bin-name-osx-normalized: "libz.dylib"
      bin-name-linux-normalized: "libz.so"
      bin-name-android-normalized: "libz.so"
      bin-name-windows-normalized: "zlib.dll"

  create-pr:
    uses: JunaMeinhold/cmake-actions/.github/workflows/create-pr.yml@v1.x.x
    needs: [build]
    with:
      lib-name: "zlib"
      lib-version: "v1.3.1"
      pr-branch: zlib-artifacts-branch
      pr-base-branch: master
      pr-reviewers: JunaMeinhold
